parameters:
    jb_simple_crud.routing_loader.class: Jb\Bundle\SimpleCrudBundle\Routing\CrudLoader
    jb_simple_crud.controller.class: Jb\Bundle\SimpleCrudBundle\Controller\CrudController
    jb_simple_crud.metadata.class: Jb\Bundle\SimpleCrudBundle\Config\CrudMetadataList
    jb_simple_crud.form.factory.class: Jb\Bundle\SimpleCrudBundle\Form\Factory\CrudFormFactory

services:
    jb_simple_crud.routing_loader:
        class: %jb_simple_crud.routing_loader.class%
        arguments:
            - %jb_simple_crud.entities%
            - @jb_simple_crud.metadata_list
        tags:
            - { name: routing.loader }

    jb_simple_crud.metadata_list:
        class: %jb_simple_crud.metadata.class%

    jb_simple_crud.controller:
        class: %jb_simple_crud.controller.class%
        arguments:
            - @doctrine
            - @jb_simple_crud.metadata_list
            - @templating
            - @jb_simple_crud.form.factory

    jb_simple_crud.form.factory:
        class: %jb_simple_crud.form.factory.class%
        arguments:
            - @form.factory