parameters:
    jb_simple_crud.submit_action.default.class: Jb\Bundle\SimpleCrudBundle\Form\Submit\DefaultSubmitAction

services:
    jb_simple_crud.submit_action.default:
        class: %jb_simple_crud.submit_action.default.class%
        arguments:
            - @doctrine
            - @jb_simple_crud.router
        tags:
            -  { name: jb_simple_crud.submit_action, alias: default }